PROJECT_HOME = ../../..
BUILD_DIR ?= $(PROJECT_HOME)/build/make

OUTDIR_SUFFIX = .nano
include $(BUILD_DIR)/make.defs

CPPFLAGS += -DMOCA_RPC_NANO
CPPSRCS += RPCProtocol.cc RPCChannelNano.cc RPCChannelEasy.cc RPCLogging.cc RPCNano.cc
INCLUDE_DIRS += ../include

SOTARGET = MocaRPCNano
LIB_NAME = MocaRPCNano

DEPLIBS += z

ifeq ($(PLATFORM), __LINUX__)
	DEPLIBS += uuid
endif

include $(BUILD_DIR)/make.rules
