/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_moca_rpc_nano_RPC */

#ifndef _Included_com_moca_rpc_nano_RPC
#define _Included_com_moca_rpc_nano_RPC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_moca_rpc_nano_RPC
 * Method:    doCreate
 * Signature: (Ljava/lang/String;JJLcom/moca/rpc/RPC;)V
 */
JNIEXPORT void JNICALL Java_com_moca_rpc_nano_RPC_doCreate
  (JNIEnv *, jclass, jstring, jlong, jlong, jobject);

/*
 * Class:     com_moca_rpc_nano_RPC
 * Method:    doDestroy
 * Signature: (Lcom/moca/rpc/RPC;J)V
 */
JNIEXPORT void JNICALL Java_com_moca_rpc_nano_RPC_doDestroy
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     com_moca_rpc_nano_RPC
 * Method:    doGetLocalAddress
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_moca_rpc_nano_RPC_doGetLocalAddress
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_moca_rpc_nano_RPC
 * Method:    doGetLocalPort
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_moca_rpc_nano_RPC_doGetLocalPort
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_moca_rpc_nano_RPC
 * Method:    doGetRemoteAddress
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_moca_rpc_nano_RPC_doGetRemoteAddress
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_moca_rpc_nano_RPC
 * Method:    doGetRemotePort
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_moca_rpc_nano_RPC_doGetRemotePort
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_moca_rpc_nano_RPC
 * Method:    doGetLocalId
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_moca_rpc_nano_RPC_doGetLocalId
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_moca_rpc_nano_RPC
 * Method:    doGetRemoteId
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_moca_rpc_nano_RPC_doGetRemoteId
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_moca_rpc_nano_RPC
 * Method:    doLoop
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_moca_rpc_nano_RPC_doLoop
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_moca_rpc_nano_RPC
 * Method:    doBreakLoop
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_moca_rpc_nano_RPC_doBreakLoop
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_moca_rpc_nano_RPC
 * Method:    doKeepAlive
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_moca_rpc_nano_RPC_doKeepAlive
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_moca_rpc_nano_RPC
 * Method:    doResponse
 * Signature: (JJI[Lcom/moca/rpc/KeyValuePair;[BII)V
 */
JNIEXPORT void JNICALL Java_com_moca_rpc_nano_RPC_doResponse
  (JNIEnv *, jclass, jlong, jlong, jint, jobjectArray, jbyteArray, jint, jint);

/*
 * Class:     com_moca_rpc_nano_RPC
 * Method:    doRequest
 * Signature: (JI[Lcom/moca/rpc/KeyValuePair;[BII)V
 */
JNIEXPORT void JNICALL Java_com_moca_rpc_nano_RPC_doRequest
  (JNIEnv *, jclass, jlong, jint, jobjectArray, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
